URL_SERVICE = "https://3d871335-4b0e-4e69-b7ea-d3bf6008e384.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users"
PRODUCTS_KITS_PATH = "/api/v1/products/kits"
CREATE_KITS_PATH = "/api/v1/kits"